package deals.entity;
import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {

     private Integer id;
     private Countries countries;
     private String name;
     private String lat;
     private String lon;
     private String currency;
     private Set dealses = new HashSet(0);

    public Cities() {
    }

	
    public Cities(Countries countries, String name, String currency) {
        this.countries = countries;
        this.name = name;
        this.currency = currency;
    }
    public Cities(Countries countries, String name, String lat, String lon, String currency, Set dealses) {
       this.countries = countries;
       this.name = name;
       this.lat = lat;
       this.lon = lon;
       this.currency = currency;
       this.dealses = dealses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public Set getDealses() {
        return this.dealses;
    }
    
    public void setDealses(Set dealses) {
        this.dealses = dealses;
    }




}


