package deals.entity;


import java.util.HashSet;
import java.util.Set;
import org.codehaus.jackson.annotate.JsonAutoDetect;
import org.codehaus.jackson.annotate.JsonAutoDetect.Visibility;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Countries generated by hbm2java
 */
@JsonAutoDetect(fieldVisibility = Visibility.NONE , getterVisibility = Visibility.NONE , isGetterVisibility = Visibility.NONE , setterVisibility = Visibility.NONE)
public class Countries  implements java.io.Serializable {

@JsonProperty()
     private String code;
@JsonProperty()
     private String name;
@JsonProperty()
     private Set citieses = new HashSet(0);

    public Countries() {
    }

	
    public Countries(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Countries(String code, String name, Set citieses) {
       this.code = code;
       this.name = name;
       this.citieses = citieses;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCitieses() {
        return this.citieses;
    }
    
    public void setCitieses(Set citieses) {
        this.citieses = citieses;
    }




}


