package deals.entity;
// Generated 25/11/2011 06:43:42 � by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Deals generated by hbm2java
 */
public class Deals  implements java.io.Serializable {
 public  enum FromSite{dealgobbler,gonabit,cobone,fustuq,makhsoom,groupon,offerna,yallabuyit,souq,nailthedeal}

     private Integer id;
     private Cities cities;
     private Language language;
     private String title;
     private String description;
     private BigDecimal value;
     private BigDecimal discount;
     private BigDecimal price;
     private BigDecimal saving;
     private Date end;
     private String url;
     private String photo;
     private int views;
     private int bestDeal;
     private String currency;
     private String fromSite;

    public Deals() {
    }

	
    public Deals(Language language, int views, int bestDeal, String currency) {
        this.language = language;
        this.views = views;
        this.bestDeal = bestDeal;
        this.currency = currency;
    }
    public Deals(Cities cities, Language language, String title, String description, BigDecimal value, BigDecimal discount, BigDecimal price, BigDecimal saving, Date end, String url, String photo, int views, int bestDeal, String currency) {
       this.cities = cities;
       this.language = language;
       this.title = title;
       this.description = description;
       this.value = value;
       this.discount = discount;
       this.price = price;
       this.saving = saving;
       this.end = end;
       this.url = url;
       this.photo = photo;
       this.views = views;
       this.bestDeal = bestDeal;
       this.currency = currency;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getSaving() {
        return this.saving;
    }
    
    public void setSaving(BigDecimal saving) {
        this.saving = saving;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public int getViews() {
        return this.views;
    }
    
    public void setViews(int views) {
        this.views = views;
    }
    public int getBestDeal() {
        return this.bestDeal;
    }
    
    public void setBestDeal(int bestDeal) {
        this.bestDeal = bestDeal;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getFromSite() {
        return fromSite;
    }

    public void setFromSite(String fromSite) {
        this.fromSite = fromSite;
    }

}


