package deals.entity;


import java.util.HashSet;
import java.util.Set;
import org.codehaus.jackson.annotate.JsonAutoDetect;
import org.codehaus.jackson.annotate.JsonAutoDetect.Visibility;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Language generated by hbm2java
 */
@JsonAutoDetect(fieldVisibility = Visibility.NONE , getterVisibility = Visibility.NONE , isGetterVisibility = Visibility.NONE , setterVisibility = Visibility.NONE)
public class Language  implements java.io.Serializable {

@JsonProperty()
     private Integer id;
@JsonProperty()
     private String name;
@JsonProperty()
     private int defualtLanguage;

     private Set dealses = new HashSet(0);

    public Language() {
    }

	
    public Language(String name, int defualtLanguage) {
        this.name = name;
        this.defualtLanguage = defualtLanguage;
    }
    public Language(String name, int defualtLanguage, Set dealses) {
       this.name = name;
       this.defualtLanguage = defualtLanguage;
       this.dealses = dealses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getDefualtLanguage() {
        return this.defualtLanguage;
    }
    
    public void setDefualtLanguage(int defualtLanguage) {
        this.defualtLanguage = defualtLanguage;
    }
    public Set getDealses() {
        return this.dealses;
    }
    
    public void setDealses(Set dealses) {
        this.dealses = dealses;
    }




}


