package deals.entity;
// Generated 25/11/2011 06:43:42 ã by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int defualtLanguage;
     private Set dealses = new HashSet(0);

    public Language() {
    }

	
    public Language(String name, int defualtLanguage) {
        this.name = name;
        this.defualtLanguage = defualtLanguage;
    }
    public Language(String name, int defualtLanguage, Set dealses) {
       this.name = name;
       this.defualtLanguage = defualtLanguage;
       this.dealses = dealses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getDefualtLanguage() {
        return this.defualtLanguage;
    }
    
    public void setDefualtLanguage(int defualtLanguage) {
        this.defualtLanguage = defualtLanguage;
    }
    public Set getDealses() {
        return this.dealses;
    }
    
    public void setDealses(Set dealses) {
        this.dealses = dealses;
    }




}


